### PR TITLE
fix performance, and possibly plugin conflicts, by not calling get forms directly on every class constructor

### PR DESCRIPTION
**Pull request by menno-ll**
The get_forms function was called a lot inside of a constructor.
This is kind of okay for small sites, but for a site with 200 forms, this is a large query to do. It's even worse, because GravityForms runs a separate query for each form.

That's why i moved this functionality to a separate function, which will only get the forms once.

This also possibly solves some plugin conflicts, like for example https://github.com/DannyvanHolten/acf-gravityforms-add-on/issues/25 .

I see the checks are failing, but i also see that i may destroy code consistency in your plugin if i try to comply to them.
If you're sure you want me to comply, please let me know.

### CODE REVIEW

**Comment by markhowellsmead** [comment]
Thanks for the suggestion. I'll take a look at it once all the other changes are merged in.

**Comment by menno-ll** [comment]
Awesome! Please keep me posted :), and feel free to ask if there're any questions

**Comment by markhowellsmead** [comment]
See #40.

**Comment by menno-ll** [comment]
Thank you for the update! :)

**Pull request closed without merging**
