### PR TITLE
Update Field.php

### PR DESCRIPTION
**Pull request by rachelbilski**
default value field added, numerical field (choose form id number)

### CODE REVIEW

**Comment by mmirus** [comment]
This fork closes #18.

**Comment by markhowellsmead** [comment]
I'll review this once #29 is resolved.

**Comment by markhowellsmead** [comment]
@rachelbilski @mmirus I have manually merged in a number of pending code amendments. Due to the age of the change requests, I would greatly appreciate it if you could install 1.2.5 from Github and let me know if the issues mentioned here are resolved. Many thanks! @rachelbilski The default value isn't implemented yet; I'll add it once all the other changes are implemented.

**Comment by markhowellsmead** [comment]
@rachelbilski @mmirus Can you give me some feedback on version 1.2.5 (available only through Github) please? Many thanks.

**Comment by markhowellsmead** [comment]
No further response. Please test using the latest plugin version.

**Pull request closed without merging**
