### PR TITLE
adds ability to disable the option field

### PR DESCRIPTION
**Pull request by nathanpowelldev**
This allows developers to disable the field via the `disabled` setting.

### CODE REVIEW

**Comment by markhowellsmead** [comment]
I don't understand what this achieves. Providing the editor with a field which can only be used once doesn't make sense.

**Comment by markhowellsmead** [comment]
That's very niche and I don't think it's a suitable addition to the plugin. Perhaps you can achieve the same goal by using one of ACF's filters.

**Comment by nathanpowelldev** [comment]
Doesn't look like it. Thanks for your attention.

**Comment by markhowellsmead** [comment]
Version 1.3.2 in Github now has a filter, with which you can modify the HTML output of the field. https://github.com/DannyvanHolten/acf-gravityforms-add-on/blob/master/resources/Field.php#L153 If this works for you, I'll update the plugin at wordpress.org.

**Comment by nathanpowelldev** [comment]
Thank you. I could probably do something with that. Would be VERY helpful if `$fieldOptions` was passed in separately as an argument as well, but I won't complain. I can use something like DOMDocument to manipulate what I need to.

**Comment by markhowellsmead** [comment]
That’s done. The hook is now renamed to 'acf-gravityforms-add-on/field_html'. I'll push it to WordPress shortly.

**Comment by nathanpowelldev** [comment]
You are amazing my friend! Thank you very much! You just made my weekend ;)

**Comment by nathanpowelldev** [comment]
FYI, I updated to 1.3.3 via wordpress.org and it does not reflect this change.

**Comment by markhowellsmead** [comment]
Please try 1.3.4.

**Comment by nathanpowelldev** [comment]
This version allows me to do what I need. Thank you for the updates.

**Pull request closed without merging**
